app_name: chs-streaming-api-frontend
group: streampath
weight: 200
routes:
   1: ^/streaming-api-cache/filings
   2: ^/streaming-api-cache/companies
   3: ^/streaming-api-cache/insolvency-cases
   4: ^/streaming-api-cache/charges
   5: ^/streaming-api-cache/officers
   6: ^/streaming-api-cache/persons-with-significant-control